-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [vault_formula]: function definitions
module
public import Aeneas
public import VaultFormula.Types
public import VaultFormula.FunsExternal
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace vault_formula

/-- [vault_formula::formula::BPS]
    Source: 'src/../../../packages/vault-core/src/math/formula.rs', lines 10:0-10:29
    Visibility: public -/
@[global_simps, irreducible] def formula.BPS : Std.U128 := 10000#u128

/-- [vault_formula::formula::YEAR]
    Source: 'src/../../../packages/vault-core/src/math/formula.rs', lines 12:0-12:42
    Visibility: public -/
@[global_simps, irreducible]
def formula.YEAR : Result Std.U128 := do
  let i ← 365#u128 * 24#u128
  let i1 ← i * 60#u128
  i1 * 60#u128

/-- [vault_formula::formula::mul_div]:
    Source: 'src/../../../packages/vault-core/src/math/formula.rs', lines 15:0-17:1 -/
def formula.mul_div
  (a : Std.U64) (b : Std.U128) (d : Std.U128) : Result (Option Std.U64) := do
  let i ← lift (UScalar.cast .U128 a)
  let o ← lift (U128.checked_mul i b)
  let cf ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let i1 ← val / d
    let r ← U64.Insts.CoreConvertTryFromU128TryFromIntError.try_from i1
    core.result.Result.ok r
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionNever.from_residual
      Std.U64 residual

/-- [vault_formula::formula::mul_div_ceil]:
    Source: 'src/../../../packages/vault-core/src/math/formula.rs', lines 20:0-22:1 -/
def formula.mul_div_ceil
  (a : Std.U64) (b : Std.U128) (d : Std.U128) : Result (Option Std.U64) := do
  let i ← lift (UScalar.cast .U128 a)
  let o ← lift (U128.checked_mul i b)
  let cf ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let i1 ← core.num.U128.div_ceil val d
    let r ← U64.Insts.CoreConvertTryFromU128TryFromIntError.try_from i1
    core.result.Result.ok r
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionNever.from_residual
      Std.U64 residual

/-- [vault_formula::formula::to_shares]:
    Source: 'src/../../../packages/vault-core/src/math/formula.rs', lines 26:0-28:1
    Visibility: public -/
def formula.to_shares
  (assets : Std.U64) (total_assets : Std.U64) (total_shares : Std.U64) :
  Result (Option Std.U64)
  := do
  let i ← lift (UScalar.cast .U128 total_shares)
  let i1 ← i + 1#u128
  let i2 ← lift (UScalar.cast .U128 total_assets)
  let i3 ← i2 + 1#u128
  formula.mul_div assets i1 i3

/-- [vault_formula::formula::to_shares_ceil]:
    Source: 'src/../../../packages/vault-core/src/math/formula.rs', lines 32:0-34:1 -/
def formula.to_shares_ceil
  (assets : Std.U64) (total_assets : Std.U64) (total_shares : Std.U64) :
  Result (Option Std.U64)
  := do
  let i ← lift (UScalar.cast .U128 total_shares)
  let i1 ← i + 1#u128
  let i2 ← lift (UScalar.cast .U128 total_assets)
  let i3 ← i2 + 1#u128
  formula.mul_div_ceil assets i1 i3

/-- [vault_formula::formula::to_assets]:
    Source: 'src/../../../packages/vault-core/src/math/formula.rs', lines 38:0-40:1
    Visibility: public -/
def formula.to_assets
  (shares : Std.U64) (total_assets : Std.U64) (total_shares : Std.U64) :
  Result (Option Std.U64)
  := do
  let i ← lift (UScalar.cast .U128 total_assets)
  let i1 ← i + 1#u128
  let i2 ← lift (UScalar.cast .U128 total_shares)
  let i3 ← i2 + 1#u128
  formula.mul_div shares i1 i3

/-- [vault_formula::formula::unlocked]:
    Source: 'src/../../../packages/vault-core/src/math/formula.rs', lines 46:0-52:1
    Visibility: public -/
def formula.unlocked
  (locked : Std.U64) (elapsed : Std.U64) (window : Std.U64) :
  Result Std.U64
  := do
  if elapsed >= window
  then ok locked
  else
    let i ← lift (UScalar.cast .U128 locked)
    let i1 ← lift (UScalar.cast .U128 elapsed)
    let i2 ← i * i1
    let i3 ← lift (UScalar.cast .U128 window)
    let i4 ← i2 / i3
    ok (UScalar.cast .U64 i4)

/-- [vault_formula::formula::blend]:
    Source: 'src/../../../packages/vault-core/src/math/formula.rs', lines 58:0-65:1
    Visibility: public -/
def formula.blend
  (locked : Std.U64) (time_left : Std.U64) (gain : Std.U64) (period : Std.U64)
  :
  Result Std.U64
  := do
  let i ← lift (UScalar.cast .U128 locked)
  let i1 ← lift (UScalar.cast .U128 gain)
  let total ← i + i1
  if total = 0#u128
  then ok period
  else
    let i2 ← lift (UScalar.cast .U128 locked)
    let i3 ← lift (UScalar.cast .U128 time_left)
    let i4 ← i2 * i3
    let i5 ← lift (UScalar.cast .U128 gain)
    let i6 ← lift (UScalar.cast .U128 period)
    let i7 ← i5 * i6
    let i8 ← i4 + i7
    let i9 ← i8 / total
    ok (UScalar.cast .U64 i9)

/-- [vault_formula::formula::performance_fee]:
    Source: 'src/../../../packages/vault-core/src/math/formula.rs', lines 69:0-71:1
    Visibility: public -/
def formula.performance_fee
  (gain : Std.U64) (fee_bps : Std.U16) : Result (Option Std.U64) := do
  let i ← lift (UScalar.cast .U128 fee_bps)
  formula.mul_div gain i formula.BPS

/-- [vault_formula::formula::management_fee]:
    Source: 'src/../../../packages/vault-core/src/math/formula.rs', lines 75:0-81:1
    Visibility: public -/
def formula.management_fee
  (total_assets : Std.U64) (fee_bps : Std.U16) (elapsed : Std.U64) :
  Result (Option Std.U64)
  := do
  let i ← lift (UScalar.cast .U128 fee_bps)
  let i1 ← lift (UScalar.cast .U128 elapsed)
  let o ← lift (U128.checked_mul i i1)
  let cf ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let i2 ← formula.YEAR
    let i3 ← formula.BPS * i2
    formula.mul_div total_assets val i3
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionNever.from_residual
      Std.U64 residual

/-- [vault_formula::formula::recover]:
    Source: 'src/../../../packages/vault-core/src/math/formula.rs', lines 86:0-89:1
    Visibility: public -/
def formula.recover
  (gain : Std.U64) (loss : Std.U64) : Result (Std.U64 × Std.U64) := do
  let recovered ← lift (core.cmp.impls.OrdU64.min gain loss)
  let i ← gain - recovered
  let i1 ← loss - recovered
  ok (i, i1)

/-- [vault_formula::formula::carry_elapsed]:
    Source: 'src/../../../packages/vault-core/src/math/formula.rs', lines 95:0-101:1
    Visibility: public -/
def formula.carry_elapsed
  (elapsed : Std.U64) (before : Std.U64) (after : Std.U64) :
  Result Std.U64
  := do
  if after = 0#u64
  then ok 0#u64
  else
    let i ← lift (UScalar.cast .U128 elapsed)
    let i1 ← lift (core.cmp.impls.OrdU64.min before after)
    let i2 ← lift (UScalar.cast .U128 i1)
    let i3 ← i * i2
    let i4 ← lift (UScalar.cast .U128 after)
    let i5 ← i3 / i4
    ok (UScalar.cast .U64 i5)

/-- [vault_formula::formula::fee_shares::{impl core::ops::function::FnOnce<(&'_0 u128,), bool> for vault_formula::formula::fee_shares::{closure}}::call_once]:
    Source: 'src/../../../packages/vault-core/src/math/formula.rs', lines 110:16-110:32 -/
def
  formula.fee_shares.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U128Bool.call_once
  (c : formula.fee_shares.closure) (tupled_args : Std.U128) : Result Bool := do
  ok (tupled_args > 0#u128)

/-- Trait implementation: [vault_formula::formula::fee_shares::{impl core::ops::function::FnOnce<(&'_0 u128,), bool> for vault_formula::formula::fee_shares::{closure}}]
    Source: 'src/../../../packages/vault-core/src/math/formula.rs', lines 110:16-110:32 -/
@[reducible]
def formula.fee_shares.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U128Bool
  : core.ops.function.FnOnce formula.fee_shares.closure Std.U128 Bool := {
  call_once :=
    formula.fee_shares.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U128Bool.call_once
}

/-- [vault_formula::formula::fee_shares]:
    Source: 'src/../../../packages/vault-core/src/math/formula.rs', lines 106:0-112:1
    Visibility: public -/
def formula.fee_shares
  (fee_assets : Std.U64) (total_assets : Std.U64) (total_shares : Std.U64) :
  Result (Option Std.U64)
  := do
  let i ← lift (UScalar.cast .U128 total_assets)
  let i1 ← i + 1#u128
  let i2 ← lift (UScalar.cast .U128 fee_assets)
  let o ← lift (U128.checked_sub i1 i2)
  let o1 ←
    core.option.Option.filter
      formula.fee_shares.closure.Insts.CoreOpsFunctionFnOnceTupleShared0U128Bool
      o ()
  let cf ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o1
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let i3 ← lift (UScalar.cast .U128 total_shares)
    let i4 ← i3 + 1#u128
    formula.mul_div fee_assets i4 val
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionNever.from_residual
      Std.U64 residual

/-- [vault_formula::formula::fulfil]:
    Source: 'src/../../../packages/vault-core/src/math/formula.rs', lines 118:0-125:1
    Visibility: public -/
def formula.fulfil
  (shares : Std.U64) (idle : Std.U64) (total_assets : Std.U64)
  (total_shares : Std.U64) :
  Result (Option (Std.U64 × Std.U64))
  := do
  let o ← formula.to_assets shares total_assets total_shares
  let cf ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    if val <= idle
    then ok (some (val, shares))
    else
      let o1 ← formula.to_shares_ceil idle total_assets total_shares
      let cf1 ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o1
      match cf1 with
      | core.ops.control_flow.ControlFlow.Continue val1 =>
        let i ← lift (core.cmp.impls.OrdU64.min val1 shares)
        ok (some (idle, i))
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionNever.from_residual
          (Std.U64 × Std.U64) residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionNever.from_residual
      (Std.U64 × Std.U64) residual

end vault_formula
