-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [vault_formula]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
module
public import Aeneas
public import VaultFormula.Types
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open vault_formula

/-- [core::convert::num::{impl core::convert::TryFrom<u128, core::num::error::TryFromIntError> for u64}::try_from]:
    Source: '/rustc/library/core/src/convert/num.rs', lines 383:12-383:64
    Name pattern: [core::convert::num::{core::convert::TryFrom<u64, u128, core::num::error::TryFromIntError>}::try_from]
    Visibility: public -/
@[rust_fun
  "core::convert::num::{core::convert::TryFrom<u64, u128, core::num::error::TryFromIntError>}::try_from"]
axiom U64.Insts.CoreConvertTryFromU128TryFromIntError.try_from
  :
  Std.U128 → Result (core.result.Result Std.U64
    core.num.error.TryFromIntError)

/-- [core::num::{u128}::div_ceil]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 3817:8-3817:54
    Name pattern: [core::num::{u128}::div_ceil]
    Visibility: public -/
@[rust_fun "core::num::{u128}::div_ceil"]
axiom core.num.U128.div_ceil : Std.U128 → Std.U128 → Result Std.U128

/-- [core::option::{core::option::Option<T>}::filter]:
    Source: '/rustc/library/core/src/option.rs', lines 1576:4-1579:28
    Name pattern: [core::option::{core::option::Option<@T>}::filter]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<@T>}::filter"]
axiom core.option.Option.filter
  {T : Type} {P : Type} (opsfunctionFnOncePTupleSharedTBoolInst :
  core.ops.function.FnOnce P T Bool) :
  Option T → P → Result (Option T)

/-- [core::option::{impl core::ops::try_trait::Try for core::option::Option<T>}::branch]:
    Source: '/rustc/library/core/src/option.rs', lines 2875:4-2875:64
    Name pattern: [core::option::{core::ops::try_trait::Try<core::option::Option<@T>>}::branch]
    Visibility: public -/
@[rust_fun
  "core::option::{core::ops::try_trait::Try<core::option::Option<@T>>}::branch"]
axiom core.option.Option.Insts.CoreOpsTry_traitTry.branch
  {T : Type} :
  Option T → Result (core.ops.control_flow.ControlFlow (Option Never) T)

/-- [core::option::{impl core::ops::try_trait::FromResidual<core::option::Option<!>> for core::option::Option<T>}::from_residual]:
    Source: '/rustc/library/core/src/option.rs', lines 2889:4-2889:49
    Name pattern: [core::option::{core::ops::try_trait::FromResidual<core::option::Option<@T>, core::option::Option<!>>}::from_residual]
    Visibility: public -/
@[rust_fun
  "core::option::{core::ops::try_trait::FromResidual<core::option::Option<@T>, core::option::Option<!>>}::from_residual"]
axiom
  core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionNever.from_residual
  (T : Type) : Option Never → Result (Option T)

/-- [core::result::{core::result::Result<T, E>}::ok]:
    Source: '/rustc/library/core/src/result.rs', lines 709:4-712:28
    Name pattern: [core::result::{core::result::Result<@T, @E>}::ok]
    Visibility: public -/
@[rust_fun "core::result::{core::result::Result<@T, @E>}::ok"]
axiom core.result.Result.ok
  {T : Type} {E : Type} : core.result.Result T E → Result (Option T)

