-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [vault_formula]: type definitions
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace vault_formula

/-- [vault_formula::formula::fee_shares::{closure}]
    Source: 'src/../../../packages/vault-core/src/math/formula.rs', lines 110:16-110:32 -/
@[reducible]
def formula.fee_shares.closure := Unit

end vault_formula
